name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  verify_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify NPM and Rubygem Versions Match
      run: |
      NPM_VERSION=$(cat package.json | jq -r '.version')
      GEM_VERSION=$(cat lib/dropzone_input/version.rb | awk '/VERSION/{ print $3 }' | tr -d "'")
      test $NPM_VERSION == $GEM_VERSION
