name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  verify_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify NPM and Rubygem Versions Match
      id: versions
      run: |
        NPM_VERSION=$(cat package.json | jq -r '.version')
        GEM_VERSION=$(cat lib/dropzone_input/version.rb | awk '/VERSION/{ print $3 }' | tr -d "'")
        echo "npm version: $NPM_VERSION, rubygems version: $GEM_VERSION"
        test $NPM_VERSION == $GEM_VERSION
        echo "::set-output name=version::$NPM_VERSION"
    - name: Verify Changelog Entry for Version
      run: |
        cat CHANGELOG.md | grep ${{ steps.versions.outputs.version }}

  create_release:
    needs: verify_version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: version
      run: |
        VERSION=$(cat package.json | jq -r '.version')
        echo "::set-output name=version::$VERSION"
    - name: Get version changes
      run: |
        awk -v version='[${{ steps.version.outputs.version }}]' '/^## / {printit = $2 == version}; printit;' CHANGELOG.md > RELEASE_CHANGELOG.md
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body_path: RELEASE_CHANGELOG.md
        draft: true
