name: Publish Packages
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Configure Rubygems Credentials
      run: |
        mkdir ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        EOF
        chmod 0600 ~/.gem/credentials
    - run: gem build dropzone_input.gemspec
    - uses: actions/upload-artifact@v2
      with:
        name: gem
        path: "*.gem"
    - run: "gem push *.gem"

    # Publish to NPM
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
        scope: '@darkroom-com'
    - run: npm install
    - run: npm pack
    - uses: actions/upload-artifact@v2
      with:
        name: npm
        path: "*.tgz"
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
